[build]
rustflags = ["--cfg", "tokio_unstable"]
rustc-wrapper = "/home/ubuntu/.asdf/installs/rust/1.71.1/bin/sccache"

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=mold"]
